source 'https://rubygems.org'
ruby '2.2.5'
gem 'rails', '~> 4.2.6'

gem 'thin'    # architecture: app server
gem 'sinatra', '>= 1.3.0', :require => nil # TODO: why is there another webserver? lol
gem 'mysql2'  # architecture: database
gem 'airbrake', '~> 5.4'

# middleware
gem 'rack-cors', :require => 'rack/cors'
gem 'rack-rewrite'

# libraries
gem 'aws-sdk' # TODO fix to version 1.0
gem 'aasm'
gem 'paper_trail'
gem 'static_model'
gem 'email_validator'
gem 'json'
gem 'httparty'
gem 'hpricot'
gem 'diffy'
gem 'countries', require: 'countries/global'

# Rails Plugins / Functionality
gem 'jsonapi-serializers'    # JSON serializing
gem 'devise'                 # authentication
gem 'cancancan'              # roles
gem "auto_strip_attributes"  #
gem 'paperclip'
gem 'sidekiq', "~> 3.5.4"    # background jobs
gem 'roadie-rails'           # html email helper
gem 'docusign_rest'
gem 'wicked_pdf'
gem 'paranoia'
gem 'draper'
gem 'flip'
gem 'kaminari'
gem 'remotipart', '~> 1.2'
gem 'activeadmin', github: 'activeadmin'

# User Interface
# Rails / Asset Pipeline / Build System
gem 'err_supply', git: 'https://github.com/sergio-fry/err_supply.git', ref: '5bedb73'
gem 'execjs'
gem 'coffee-rails'
gem 'uglifier'
gem 'autoprefixer-rails'
gem 'font-awesome-rails'
gem 'sass-rails'#, '>= 3.2'
gem 'haml-rails'
gem 'turbolinks', '~> 5.0.0'
gem 'cocoon'

# Functionality
gem 'kramdown'
gem 'honeypot-captcha'

# UI Libraries
gem 'formtastic'
gem 'formtastic-bootstrap'
gem 'bootstrap-sass'#, '~> 3.3.0'
gem 'bootstrap-datepicker-rails'
gem 'bootstrap3-datetimepicker-rails'

# JavaScript
gem 'jquery-rails'
gem 'jquery-tablesorter'
gem 'momentjs-rails'
gem 'gon'

source 'https://rails-assets.org' do
  gem 'rails-assets-backbone'
  gem 'rails-assets-underscore'
  gem 'rails-assets-countto'
end

group :development, :staging do
  gem 'dotenv'
  gem "mail_view"
  gem 'rubocop'
end

group :production, :staging do
  # Heroku Specific
  gem 'newrelic_rpm'
  gem 'rails_12factor'
  gem 'wkhtmltopdf-heroku'
end

group :development, :test do
  gem 'letter_opener'
  gem 'pry'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'simplecov'
  gem 'byebug'
  gem 'wkhtmltopdf-binary'
  gem 'quiet_assets'
  # Browser Testing
  gem 'capybara'
  gem 'capybara-email'
  gem 'capybara-screenshot'
  # Capybara Drivers
  gem 'poltergeist'
  # Automation
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-bundler', require: false
  gem 'guard-livereload', '~> 2.5', require: false
  gem 'rack-livereload'
  # Testing
  gem 'rspec-rails'
  gem 'rspec-retry'
  gem 'rspec-sidekiq'
  gem 'rspec-its'
  gem "factory_girl_rails"
  gem 'database_cleaner'
  gem 'shoulda', '~> 3.5.0'
  gem 'shoulda-matchers', '~> 2.8.0'
  gem 'faker'
  gem 'timecop'
  gem 'seed_dump'
end
